#-------------------------------
# General Site Settings
baseURL = "https://cloudnativecentral.com/"
languageCode = "en-us"
title = "Cloud Native Central"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 7

#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    parent = "About"
    name = "About"
    url = "/about/"
    weight = 3
    
  [[menu.main]]
    identifier = "authors"
    name = "Authors"
    url = "/authors/"
    weight = 2
 
 # Footer Menu
  [[menu.footer]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.footer]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3


[params]
  #logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  #description = "Mria is a multipurpose blog theme for HUGO"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

  #-------------------------------
  # Blog Section Settings
  [params.blog]
    enable = true
    blog__title = "Latest Posts"
    blog__description = ""

  #-------------------------------
  # Tag Section Settings
  [params.tag]
    enable = false
    tag = "containers" #


  #-------------------------------
  # Author Section Settings
  [params.author_section]
    enable = false
    author__section__title = "Hello, my name is Alena. I’m reviewer and content creator."
    author__section__description = "I’m a published content creator, brand copywriter, photographer, and social media content creator and manager. I help brands connect with their customers by developing engaging content that entertains, educates, and offers value to their audience."
    aurhor__section__button__text = "More About Me"
    aurhor__section__button__link = "/about"
    author__section__big__image = "https://via.placeholder.com/1200x800"
    author__section__small__image = "https://via.placeholder.com/1200x800"
    author__section__image__alt = "Alena Curtis"


  # Newsletter
  [params.mailchimp]
    enable = false
    mailchimp__title = "Get interesting news"
    mailchimp__description = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3" # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Subscribe"
    mailchimp__background__image = "https://via.placeholder.com/1920x1080"


  #-------------------------------
  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com/cloudnatcentral"

  # Other icons can be found at https://ionicons.com/v4/


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "ravikanth@ravichaganti.com" # Add your form_id

    # NOTE
    # Mria comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

[taxonomies]
  author = "authors"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
